// ============================================================
// CAMPUS 3D â€” the whole site as extruded massing, plus the real
// interior walls of M1â€“M4.
//
// Geometry comes from campus-data.js (CAMPUS), generated by
// tools/build_campus.py out of the CAD inside the public campus
// PDF. Coordinates are metres: [x, z] on the ground plane, y up.
//
// Footprints are real. HEIGHTS ARE NOT â€” the drawing is a single
// level. Anything with hKnown false is a guess and says so, in the
// panel and with a ~ on its label. Never let that blur.
//
// Camera is hand-rolled rather than OrbitControls, which is not on
// the CDN allowlist as a standalone file.
// ============================================================

const C = CAMPUS;
const cvs = document.getElementById("scene");
const tagBox = document.getElementById("tags");

if (typeof THREE === "undefined") {
    document.getElementById("loading").textContent =
        "three.js failed to load â€” check the network, then reload.";
    throw new Error("three.js missing");
}
document.getElementById("loading").remove();

// ---------- palette, read off the page so it tracks the theme ----------

const css = v => getComputedStyle(document.documentElement).getPropertyValue(v).trim();
const COL = () => ({
    bg: new THREE.Color(css("--bg") || "#F2EBDB"),
    ground: new THREE.Color(css("--bg-elevated") || "#EAE0C8"),
    mass: new THREE.Color(css("--bg-card") || "#FFFEFB"),
    known: new THREE.Color(css("--coral") || "#1E40AF"),
    wall: new THREE.Color(css("--fg-soft") || "#3B4659"),
    edge: new THREE.Color(css("--fg") || "#0E1726"),
});

// ---------- scene ----------

const scene = new THREE.Scene();
const renderer = new THREE.WebGLRenderer({ canvas: cvs, antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

const camera = new THREE.PerspectiveCamera(50, 1, 0.5, 6000);

const sun = new THREE.DirectionalLight(0xffffff, 0.72);
sun.position.set(-260, 420, 180);
sun.castShadow = true;
sun.shadow.mapSize.set(2048, 2048);
const S = 0;   // set once SPAN is known, below
scene.add(sun, new THREE.HemisphereLight(0xdfe6f0, 0x8b93a3, 0.42));

// The data is y-down in plan (x, z). Recentre on where the buildings actually
// are, not on the middle of the site: the drawing's extent includes car parks
// and boundary walls, so the campus proper sits well off that centre and the
// camera would open looking at empty ground.
const BB = (() => {
    let x0 = 1e9, x1 = -1e9, z0 = 1e9, z1 = -1e9;
    for (const b of C.buildings) for (const [x, z] of b.p) {
        if (x < x0) x0 = x; if (x > x1) x1 = x;
        if (z < z0) z0 = z; if (z > z1) z1 = z;
    }
    return { x0, x1, z0, z1, w: x1 - x0, d: z1 - z0 };
})();
const CX = (BB.x0 + BB.x1) / 2, CZ = (BB.z0 + BB.z1) / 2;
const SPAN = Math.max(BB.w, BB.d);

// Framing span: the middle 80% of building centroids. Keeps the two far-flung
// service buildings in the model without letting them dictate the zoom.
const FIT = (() => {
    const xs = C.buildings.map(b => b.p.reduce((a, p) => a + p[0], 0) / b.p.length).sort((a, b) => a - b);
    const zs = C.buildings.map(b => b.p.reduce((a, p) => a + p[1], 0) / b.p.length).sort((a, b) => a - b);
    const q = (a, f) => a[Math.floor((a.length - 1) * f)];
    return Math.max(q(xs, 0.9) - q(xs, 0.1), q(zs, 0.9) - q(zs, 0.1)) * 1.1;
})();

const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(SPAN * 3, SPAN * 3),
    new THREE.MeshLambertMaterial({ color: COL().ground })
);
ground.rotation.x = -Math.PI / 2;
ground.position.y = -0.05;
ground.receiveShadow = true;
scene.add(ground);

function shapeOf(poly) {
    const s = new THREE.Shape();
    poly.forEach(([x, z], i) => i ? s.lineTo(x - CX, z - CZ) : s.moveTo(x - CX, z - CZ));
    s.closePath();
    return s;
}

// extrude in the shape's own plane, then lay it down so it grows in +y
function extrude(poly, h) {
    const g = new THREE.ExtrudeGeometry(shapeOf(poly), { depth: h, bevelEnabled: false });
    g.rotateX(Math.PI / 2);
    g.translate(0, h, 0);
    return g;
}

// ---------- buildings ----------

const P = COL();
const meshes = [];
const gBuildings = new THREE.Group();
scene.add(gBuildings);

for (const b of C.buildings) {
    let g;
    try { g = extrude(b.p, b.h); } catch (e) { continue; }
    const m = new THREE.Mesh(g, new THREE.MeshLambertMaterial({ color: P.mass }));
    m.castShadow = m.receiveShadow = true;
    m.userData.b = b;
    gBuildings.add(m);
    meshes.push(m);

    // a crisp roof outline reads much better than shading alone at this scale
    const pts = b.p.map(([x, z]) => new THREE.Vector3(x - CX, b.h + 0.03, z - CZ));
    pts.push(pts[0].clone());
    gBuildings.add(new THREE.Line(
        new THREE.BufferGeometry().setFromPoints(pts),
        new THREE.LineBasicMaterial({ color: P.edge, transparent: true, opacity: 0.45 })
    ));
}

// ---------- interior walls of M1â€“M4 ----------

const gWalls = new THREE.Group();
scene.add(gWalls);
const WALL_H = 3.2;
for (const code in C.walls) {
    const mat = new THREE.MeshLambertMaterial({ color: P.wall });
    for (const poly of C.walls[code]) {
        if (poly.length < 3) continue;
        let g;
        try { g = extrude(poly, WALL_H); } catch (e) { continue; }
        const m = new THREE.Mesh(g, mat);
        m.castShadow = true;
        m.userData.code = code;
        gWalls.add(m);
    }
}

// Interior walls only make sense when the shell is out of the way, so the
// buildings that have interiors turn translucent whenever walls are shown.
const HAS_INSIDE = new Set(Object.keys(C.walls));
function applyWallMode() {
    gWalls.visible = wallsOn;
    for (const m of meshes) {
        const inside = HAS_INSIDE.has(m.userData.b.code);
        m.material.transparent = wallsOn && inside;
        m.material.opacity = (wallsOn && inside) ? 0.22 : 1;
        m.material.depthWrite = !(wallsOn && inside);
        m.material.needsUpdate = true;
    }
}

// ---------- labels ----------

const NAMES_KEY = "linkcs.campus.names";
let NAMES = {};
try { NAMES = JSON.parse(localStorage.getItem(NAMES_KEY) || "{}"); } catch (e) { NAMES = {}; }
const nameOf = b => NAMES[b.i] || b.name || b.code || null;
function saveNames() {
    try { localStorage.setItem(NAMES_KEY, JSON.stringify(NAMES)); } catch (e) { }
}

const tags = C.buildings.map(b => {
    const el = document.createElement("div");
    el.className = "tag";
    el.addEventListener("click", ev => { ev.stopPropagation(); select(b.i); });
    tagBox.appendChild(el);
    return el;
});

const _v = new THREE.Vector3();
const CENTROIDS = C.buildings.map(b => {
    let sx = 0, sz = 0;
    for (const [x, z] of b.p) { sx += x; sz += z; }
    return [sx / b.p.length - CX, sz / b.p.length - CZ];
});

// Twenty-odd tags on one screen is unreadable, so: place the biggest buildings
// first and drop any tag that would land on one already placed. A named or
// selected building always wins its slot.
function drawTags() {
    const w = cvs.clientWidth, h = cvs.clientHeight;
    const placed = [];
    const order = C.buildings.map((b, i) => i).sort((a, b) => {
        const na = nameOf(C.buildings[a]) ? 1 : 0, nb = nameOf(C.buildings[b]) ? 1 : 0;
        if (selected === a) return -1;
        if (selected === b) return 1;
        return nb - na;
    });
    for (const i of order) {
        const b = C.buildings[i], el = tags[i], n = nameOf(b);
        _v.set(CENTROIDS[i][0], b.h + 3, CENTROIDS[i][1]).project(camera);
        const x = (_v.x * 0.5 + 0.5) * w, y = (-_v.y * 0.5 + 0.5) * h;
        if (_v.z > 1 || x < -40 || y < -20 || x > w + 40 || y > h + 20) { el.style.display = "none"; continue; }
        const near = placed.some(p => Math.abs(p[0] - x) < 96 && Math.abs(p[1] - y) < 20);
        if (near && selected !== i) { el.style.display = "none"; continue; }
        placed.push([x, y]);
        el.style.display = "";
        el.style.left = x + "px";
        el.style.top = y + "px";
        el.textContent = n || "unnamed";
        el.className = "tag" + (n ? "" : " unnamed") + (b.hKnown ? "" : " guess") +
                       (selected === i ? " sel" : "");
    }
}

// ---------- camera: orbit + fly ----------

const target = new THREE.Vector3(0, 0, 0);
// The M cluster is the part that matters; everything else is context. Open on
// it, and keep the whole site one button away.
function bboxOf(pred) {
    let x0 = 1e9, x1 = -1e9, z0 = 1e9, z1 = -1e9, n = 0;
    for (const b of C.buildings) {
        if (!pred(b)) continue;
        n++;
        for (const [x, z] of b.p) {
            if (x < x0) x0 = x; if (x > x1) x1 = x;
            if (z < z0) z0 = z; if (z > z1) z1 = z;
        }
    }
    return n ? { cx: (x0 + x1) / 2 - CX, cz: (z0 + z1) / 2 - CZ,
                 span: Math.max(x1 - x0, z1 - z0) } : null;
}
const CORE = bboxOf(b => /^M[1-4]$/.test(b.code || "")) || { cx: 0, cz: 0, span: FIT };

function focus(box, phi) {
    target.set(box.cx, 0, box.cz);
    orbit = { r: box.span * 1.35, theta: -0.9, phi: phi === undefined ? 0.9 : phi };
    placeCamera();
}

let orbit = { r: CORE.span * 1.35, theta: -0.9, phi: 0.9 };

function placeCamera() {
    camera.position.set(
        target.x + orbit.r * Math.sin(orbit.phi) * Math.cos(orbit.theta),
        target.y + orbit.r * Math.cos(orbit.phi),
        target.z + orbit.r * Math.sin(orbit.phi) * Math.sin(orbit.theta)
    );
    camera.lookAt(target);
}

function resize() {
    const w = cvs.clientWidth, h = cvs.clientHeight;
    if (!w || !h) return;
    renderer.setSize(w, h, false);
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
}

let drag = null;
cvs.addEventListener("pointerdown", ev => {
    drag = { x: ev.clientX, y: ev.clientY, b: ev.button, moved: false, id: ev.pointerId,
             t: target.clone(), th: orbit.theta, ph: orbit.phi };
});
cvs.addEventListener("pointermove", ev => {
    if (!drag) return;
    const dx = ev.clientX - drag.x, dy = ev.clientY - drag.y;
    if (!drag.moved && Math.abs(dx) + Math.abs(dy) > 3) {
        drag.moved = true;
        cvs.setPointerCapture(drag.id);
        cvs.classList.add("dragging");
    }
    if (!drag.moved) return;
    if (drag.b === 2 || ev.shiftKey) {                       // pan
        const k = orbit.r * 0.0016;
        const right = new THREE.Vector3().setFromMatrixColumn(camera.matrix, 0);
        const fwd = right.clone().cross(camera.up).normalize();
        target.copy(drag.t).addScaledVector(right, -dx * k).addScaledVector(fwd, dy * k);
    } else {                                                  // orbit
        orbit.theta = drag.th + dx * 0.005;
        orbit.phi = Math.max(0.06, Math.min(1.52, drag.ph - dy * 0.005));
    }
    placeCamera();
});
cvs.addEventListener("pointerup", ev => {
    if (drag && !drag.moved && ev.button === 0) pick(ev);
    if (drag && drag.moved) cvs.releasePointerCapture(drag.id);
    drag = null;
    cvs.classList.remove("dragging");
});
cvs.addEventListener("pointercancel", () => { drag = null; cvs.classList.remove("dragging"); });
cvs.addEventListener("contextmenu", ev => ev.preventDefault());
cvs.addEventListener("wheel", ev => {
    ev.preventDefault();
    orbit.r = Math.max(8, Math.min(SPAN * 3.5, orbit.r * Math.exp(ev.deltaY * 0.0011)));
    placeCamera();
}, { passive: false });

// WASD fly: move the orbit target, camera follows
const keys = new Set();
addEventListener("keydown", ev => {
    if (/^(Input|Select|Textarea)$/i.test(ev.target.tagName)) return;
    if ("wasdqe".includes(ev.key.toLowerCase())) { keys.add(ev.key.toLowerCase()); ev.preventDefault(); }
});
addEventListener("keyup", ev => keys.delete(ev.key.toLowerCase()));
addEventListener("blur", () => keys.clear());

function fly(dt) {
    if (!keys.size) return;
    const sp = (keys.has("shift") ? 3 : 1) * Math.max(14, orbit.r * 0.55) * dt;
    const fwd = new THREE.Vector3(Math.cos(orbit.theta), 0, Math.sin(orbit.theta)).negate();
    const right = new THREE.Vector3(-fwd.z, 0, fwd.x);
    if (keys.has("w")) target.addScaledVector(fwd, sp);
    if (keys.has("s")) target.addScaledVector(fwd, -sp);
    if (keys.has("a")) target.addScaledVector(right, -sp);
    if (keys.has("d")) target.addScaledVector(right, sp);
    if (keys.has("e")) target.y += sp;
    if (keys.has("q")) target.y -= sp;
    placeCamera();
}
addEventListener("keydown", ev => { if (ev.key === "Shift") keys.add("shift"); });
addEventListener("keyup", ev => { if (ev.key === "Shift") keys.delete("shift"); });

// ---------- picking ----------

const ray = new THREE.Raycaster();
const ndc = new THREE.Vector2();
function pick(ev) {
    const r = cvs.getBoundingClientRect();
    ndc.set(((ev.clientX - r.left) / r.width) * 2 - 1, -((ev.clientY - r.top) / r.height) * 2 + 1);
    ray.setFromCamera(ndc, camera);
    const hit = ray.intersectObjects(meshes, false)[0];
    select(hit ? hit.object.userData.b.i : null);
}

let selected = null;
function select(i) {
    selected = i;
    for (const m of meshes) {
        const on = m.userData.b.i === i;
        m.material.color.copy(on ? P.known : P.mass);
    }
    renderSide();
}

// ---------- side panel ----------

// Rooms the timetable knows about, per building, so a click can answer
// "what is actually in here" rather than just "this is a box".
const ROOMS_BY_BLDG = (() => {
    const by = {};
    for (const [, , , , room] of OCC) {
        const b = (room.match(/^(M\d)-/) || [])[1];
        if (!b) continue;
        (by[b] = by[b] || new Set()).add(room);
    }
    return Object.fromEntries(Object.entries(by).map(([k, v]) => [k, [...v].sort()]));
})();

const SLOTS = (() => {
    const map = new Map();
    for (const [day, s, e, code, room] of OCC) {
        const k = [day, s, e, code, room].join("|");
        if (!map.has(k)) map.set(k, { day, room, from: tmin(s), to: tmin(e), code, e });
    }
    return [...map.values()];
})();

function liveState(room) {
    const now = new Date();
    if (now.getDay() < 1 || now.getDay() > 5 || NO_CLASS[ymd(now)]) return null;
    const mins = now.getHours() * 60 + now.getMinutes();
    return SLOTS.find(s => s.room === room && s.day === now.getDay() && mins >= s.from && mins < s.to) || false;
}

let labelling = false;

function renderSide() {
    const side = document.getElementById("cmp-side");
    if (selected === null) {
        side.innerHTML = `<p class="side-empty">Click a building.${labelling ? " Then give it a name." : ""}</p>`;
        drawTags();
        return;
    }
    const b = C.buildings[selected];
    const n = nameOf(b);
    let h = `<h3 class="side-name">${n || "Unnamed building"}</h3>`;
    h += `<div class="side-code">${b.code ? b.code + " Â· " : ""}footprint #${b.i}</div>`;

    const area = Math.abs(b.p.reduce((a, p, k, arr) => {
        const q = arr[(k + 1) % arr.length];
        return a + (p[0] * q[1] - q[0] * p[1]);
    }, 0) / 2);
    h += `<div class="side-meta">${area.toFixed(0)} mÂ² footprint<br>` +
         `${b.storeys} storeys Â· ${b.h} m ` +
         (b.hKnown ? `<br>height from a known storey count`
                   : `<br><span class="warn">height is a guess</span>`) + `</div>`;

    const rooms = ROOMS_BY_BLDG[b.code];
    if (rooms) {
        h += `<div class="side-rooms"><h4>timetabled rooms</h4>`;
        for (const r of rooms) {
            const st = liveState(r);
            const cls = st ? "busy" : st === false ? "free" : "";
            const what = st ? `${st.code} till ${t12(st.e)}` : st === false ? "free" : "";
            h += `<div class="rrow ${cls}"><span class="c">${r}</span>` +
                 `<span class="n">${ROOM_NAMES[r] || ""}${what ? " Â· " + what : ""}</span></div>`;
        }
        h += `</div>`;
        if (b.code === "M4") h += `<p style="margin:10px 0 0"><a href="plan.html" class="cmp-btn" style="display:inline-block;text-decoration:none">open M4 floor plan â†’</a></p>`;
    }

    if (labelling) {
        h += `<div class="lbl-box"><h4>name this building</h4>
              <input id="lbl-in" value="${(NAMES[b.i] || b.name || "").replace(/"/g, "&quot;")}" placeholder="e.g. Library, MDH, MF2">
              <div class="lbl-actions">
                <button class="cmp-btn" id="lbl-clear">clear</button>
                <button class="cmp-btn" id="lbl-copy">copy all</button>
              </div>
              <div class="lbl-count">${C.buildings.filter(x => nameOf(x)).length} of ${C.buildings.length} named</div></div>`;
    }
    side.innerHTML = h;

    const inp = document.getElementById("lbl-in");
    if (inp) {
        inp.addEventListener("input", () => {
            if (inp.value.trim()) NAMES[b.i] = inp.value.trim(); else delete NAMES[b.i];
            saveNames(); drawTags();
        });
        document.getElementById("lbl-clear").addEventListener("click", () => {
            delete NAMES[b.i]; saveNames(); renderSide();
        });
        document.getElementById("lbl-copy").addEventListener("click", ev => {
            const txt = "const BUILDING_NAMES = " + JSON.stringify(NAMES, null, 4) + ";";
            navigator.clipboard.writeText(txt).then(
                () => { ev.target.textContent = "copied âœ“"; setTimeout(() => ev.target.textContent = "copy all", 1400); },
                () => { console.log(txt); ev.target.textContent = "see console"; });
        });
    }
    drawTags();
}

// ---------- toolbar ----------

let wallsOn = true;
document.getElementById("btn-walls").addEventListener("click", ev => {
    wallsOn = !wallsOn;
    ev.target.classList.toggle("on", wallsOn);
    applyWallMode();
});
const viewBtns = ["btn-core", "btn-all", "btn-top"];
function setView(id) { for (const b of viewBtns) document.getElementById(b).classList.toggle("on", b === id); }
document.getElementById("btn-core").addEventListener("click", () => { focus(CORE); setView("btn-core"); });
document.getElementById("btn-all").addEventListener("click", () => {
    focus({ cx: 0, cz: 0, span: FIT * 0.85 }); setView("btn-all");
});
document.getElementById("btn-top").addEventListener("click", () => {
    const box = document.getElementById("btn-all").classList.contains("on")
        ? { cx: 0, cz: 0, span: FIT * 0.85 } : CORE;
    focus(box, 0.06); setView("btn-top");
});
document.getElementById("btn-label").addEventListener("click", ev => {
    labelling = !labelling;
    ev.target.classList.toggle("on", labelling);
    renderSide();
});
document.getElementById("theme-toggle")?.addEventListener("click", () => {
    const cur = document.documentElement.getAttribute("data-theme") === "dark" ? "light" : "dark";
    document.documentElement.setAttribute("data-theme", cur);
    try { localStorage.setItem("theme", cur); } catch (e) { }
    setTimeout(retheme, 30);
});

function retheme() {
    const p = COL();
    Object.assign(P, p);
    scene.background = p.bg;
    ground.material.color.copy(p.ground);
    for (const m of meshes) m.material.color.copy(m.userData.b.i === selected ? p.known : p.mass);
    for (const m of gWalls.children) m.material.color.copy(p.wall);
}

// ---------- go ----------

scene.background = P.bg;
target.set(CORE.cx, 0, CORE.cz);
sun.position.set(CORE.cx - SPAN * 0.5, SPAN * 0.9, CORE.cz + SPAN * 0.35);
const SH = SPAN * 0.75;
sun.target.position.set(CORE.cx, 0, CORE.cz);
scene.add(sun.target);
Object.assign(sun.shadow.camera, { left: -SH, right: SH, top: SH, bottom: -SH, near: 1, far: SPAN * 3 });
sun.shadow.camera.updateProjectionMatrix();
applyWallMode();
resize();
placeCamera();
new ResizeObserver(resize).observe(cvs);

let last = performance.now();
(function loop(t) {
    requestAnimationFrame(loop);
    const dt = Math.min(0.05, (t - last) / 1000); last = t;
    fly(dt);
    renderer.render(scene, camera);
    drawTags();
})(last);

renderSide();
